### ISSUE TITLE
Rewording error messages, and "quiet" mode

### ISSUE THREAD

**Issue by gciolli** [2ndquadrant-it/barman-cli#1]
In version 1.1 the error message from barman-wal-restore is as follows:

> ERROR: WAL file '000000070000000000000011' not found in server 'vm96'
> ERROR: Remote 'barman get-wal' command has failed!

As some errors are not meaning that there is anything wrong, being in fact expected (i.e. when PostgreSQL tries to retrieve the next WAL, or a history file, to check whether they exist) we could suppress the second line.
The first line could also be rewritten to mention the name of the tool, so the DBA would understand immediately the context of the message. For instance, something like

> ERROR: barman-wal-restore: WAL file '000000070000000000000011' not found in server 'vm96'

**Comment by gciolli** [comment]
Moreover, I would change ERROR: into LOG:, given that in most cases the message will not come with an error condition.

**Comment by mnencia** [comment]
I'm going to disable this repository, as the code has been integrated into barman. IF the issue is still relevant please reopen it on Barman core repository.
